server:
  port: 8181
  servlet:
    context-path: /shiro

spring:
  application:
    name: shiro
  mvc:
    view:
      prefix: /  #前缀
      suffix: .jsp #后缀
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?characterEncoding=UTF-8
    username: root
    password: root


mybatis:
  type-aliases-package: com.xykj.springshiro.entity #实体扫描
  mapper-locations: classpath:/mapper/*.xml #mapper文件
